# Generated by Django 2.2.3 on 2019-09-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_testobja_second_fk_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='testobja',
            name='call_count',
            field=models.IntegerField(default=0),
        ),
    ]
