version: 2
jobs:
  build-v2.2:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command:
            echo 'export TAG=0.1.$CIRCLE_BUILD_NUM' >> $BASH_ENV
            echo 'export DJ_VERSION=2.2.3' >> $BASH_ENV
      - run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/. --build-arg DJ_VERSION=${DJ_VERSION}
      - run: |
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
  build-v2.1:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command:
            echo 'export TAG=0.1.$CIRCLE_BUILD_NUM' >> $BASH_ENV
            echo 'export DJ_VERSION=2.1' >> $BASH_ENV
      - run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/. --build-arg DJ_VERSION=${DJ_VERSION}
      - run: |
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
  build-v2.0:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export TAG=0.1.$CIRCLE_BUILD_NUM' >> $BASH_ENV
            echo 'export DJ_VERSION=2.0' >> $BASH_ENV
      - run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/. --build-arg DJ_VERSION=${DJ_VERSION}
      - run: |
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
  build-v1.10:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export TAG=0.1.$CIRCLE_BUILD_NUM' >> $BASH_ENV
            echo 'export DJ_VERSION=1.10' >> $BASH_ENV
      - run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/. --build-arg DJ_VERSION=${DJ_VERSION}
      - run: |
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-v1.10:
          filters:
            branches:
              only: master
      - build-v2.0:
          filters:
            branches:
              only: master
      - build-v2.1:
          filters:
            branches:
              only: master
      - build-v2.2:
          filters:
            branches:
              only: master