version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/.
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test