version: 2
jobs:
  build-v2.2:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            DJ_VERSION=2.2.3
      - run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/.
      - run: |
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
  build-v2.1:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            DJ_VERSION=2.1
      - run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/.
      - run: |
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
  build-v2.0:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            DJ_VERSION=2.0
      - run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/.
      - run: |
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
  build-v1.11:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            DJ_VERSION=1.11
      - run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/.
      - run: |
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
  build-v1.10:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            DJ_VERSION=1.10
      - run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/.
      - run: |
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build-v1.10
      - build-v1.11
      - build-v2.0
      - build-v2.1
      - build-v2.2