# Generated by Django 3.0 on 2020-03-14 09:44

from django.db import migrations


def forward_migration(apps, schema_editor):
    # can be ignored since this is the "clean up" migration
    pass


def backward_migration(apps, schema_editor):
    test_obj_a_class = apps.get_model('test_app', 'TestObjA')
    test_objs = test_obj_a_class.objects.all()
    for obj in test_objs:
        obj.name = f'{obj.first_name}{obj.last_name}'
        obj.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20200314_0943'),
    ]

    operations = [
        migrations.RunPython(forward_migration, backward_migration),
        migrations.RemoveField(
            model_name='testobja',
            name='name',
        ),
    ]
