# Generated by Django 3.0 on 2020-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app_fk', '0002_depmodfk_new_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_field', models.BooleanField(default=True)),
            ],
        ),
    ]
