# Generated by Django 2.2.3 on 2019-07-03 17:31

from django.db import migrations


def forward_migration(apps, schema_editor):
    # can be ignored since this is the "clean up" migration
    pass


def backward_migration(apps, schema_editor):
    test_obj_a_class = apps.get_model('tests', 'TestObjA')
    test_objs = test_obj_a_class.objects.all()
    for obj in test_objs:
        obj.name = f'{obj.first_name}{obj.last_name}'
        obj.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20190703_1731'),
    ]

    operations = [
        migrations.RunPython(
            forward_migration, backward_migration
        ),
        migrations.RemoveField(
            model_name='testobja',
            name='name',
        ),
    ]
