on: [pull_request]
jobs:
  test-dj-3-versions:
    name: Test Django 3 versions support
    runs-on: ubuntu-latest
    env:
      TAG: 0.4.0.${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Django==3.2.18
        env:
          DJ_VERSION: 3.2.18
        run: |
          docker build -t dj-migration-test/example_proj_django_3:$TAG ./examples/example_proj_django_3/. --build-arg DJ_VERSION=${DJ_VERSION}
          docker run dj-migration-test/example_proj_django_3:$TAG ./manage.py test

  test-dj-4-versions:
    name: Test Django 4 versions support
    runs-on: ubuntu-latest
    env:
      TAG: 0.4.0.${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Django==4.0.10
        env:
          DJ_VERSION: 4.0.10
        run: |
          docker build -t dj-migration-test/example_proj_django_3:$TAG ./examples/example_proj_django_3/. --build-arg DJ_VERSION=${DJ_VERSION}
          docker run dj-migration-test/example_proj_django_3:$TAG ./manage.py test

      - name: Django==4.1.7
        env:
          DJ_VERSION: 4.1.7
        run: |
          docker build -t dj-migration-test/example_proj_django_3:$TAG ./examples/example_proj_django_3/. --build-arg DJ_VERSION=${DJ_VERSION}
          docker run dj-migration-test/example_proj_django_3:$TAG ./manage.py test
