on: [pull_request]
jobs:
  test-dj-versions:
    name: Test Django versions support
    runs-on: ubuntu-18.04
    env:
      TAG: 0.1.${{ github.sha }}
    steps:
      - uses: actions/checkout@v1
      - name: Django==2.2
        env:
          DJ_VERSION: 2.2
        run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/. --build-arg DJ_VERSION=${DJ_VERSION}
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
      - name: Django==2.1
        env:
          DJ_VERSION: 2.1
        run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/. --build-arg DJ_VERSION=${DJ_VERSION}
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
      - name: Django==2.0
        env:
          DJ_VERSION: 2.0
        run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/. --build-arg DJ_VERSION=${DJ_VERSION}
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
      - name: Django==1.10
        env:
          DJ_VERSION: 1.10.8
        run: |
          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/. --build-arg DJ_VERSION=${DJ_VERSION}
          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
#      - name: Django==1.11
#        env:
#          DJ_VERSION: 1.11
#        run: |
#          docker build -t dj-migration-test/example_proj:$TAG ./examples/example_proj/. --build-arg DJ_VERSION=${DJ_VERSION}
#          docker run dj-migration-test/example_proj:$TAG python /code/manage.py test
